// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZ1BPiNDczwj5lPj_1Yqp66bzIXNTQOQ',
    appId: '1:773892008765:web:41560839800cf80996f354',
    messagingSenderId: '773892008765',
    projectId: 'fir-ai-9862a',
    authDomain: 'fir-ai-9862a.firebaseapp.com',
    storageBucket: 'fir-ai-9862a.appspot.com',
    measurementId: 'G-SQ1YCCC2S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18BpUTmWD9smek_o2WsOiR1c21fvbh2k',
    appId: '1:773892008765:android:91baebb1c166f36996f354',
    messagingSenderId: '773892008765',
    projectId: 'fir-ai-9862a',
    storageBucket: 'fir-ai-9862a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWEeY9w1bKcbHhhxERbi5fDOP_ZXh_yM4',
    appId: '1:773892008765:ios:1955e0b4698d037b96f354',
    messagingSenderId: '773892008765',
    projectId: 'fir-ai-9862a',
    storageBucket: 'fir-ai-9862a.appspot.com',
    iosBundleId: 'com.example.aiWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWEeY9w1bKcbHhhxERbi5fDOP_ZXh_yM4',
    appId: '1:773892008765:ios:1955e0b4698d037b96f354',
    messagingSenderId: '773892008765',
    projectId: 'fir-ai-9862a',
    storageBucket: 'fir-ai-9862a.appspot.com',
    iosBundleId: 'com.example.aiWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmZ1BPiNDczwj5lPj_1Yqp66bzIXNTQOQ',
    appId: '1:773892008765:web:c6dff4fc7c38a78696f354',
    messagingSenderId: '773892008765',
    projectId: 'fir-ai-9862a',
    authDomain: 'fir-ai-9862a.firebaseapp.com',
    storageBucket: 'fir-ai-9862a.appspot.com',
    measurementId: 'G-82YV5PF64F',
  );
}
